### ISSUE TITLE
The sting stays stuck 5/5 what is the reason

### ISSUE THREAD

**Issue by alexofalger2026** [TheGamerDog/PluFire#1]
The sting stays stuck 5/5 what is the reason
![Capture d'écran 2024-12-12 135257](https://github.com/user-attachments/assets/13e00d8e-5798-4bc6-8a03-00ae48003d9f)
From the best video mode explaining the operation of the game we are players who have no programming experience
And thank you too,  back our childhood memories

**Comment by Dagher69** [comment]
where's the video?

**Comment by TheGamerDog** [comment]
The instructions describe everything in as much detail as possible, re-read.
